### PR TITLE
Fixes a potential NPE when calling getPlayerHologram at the wrong time

### PR DESCRIPTION
**Pull request by RealGatt**
This PR validates that a given `Player` object isn't null, so the following error doesn't fire-

```
java.lang.NullPointerException
at net.jitse.npclib.internal.NPCBase.getPlayerHologram(NPCBase.java:70) ~[?:?]
at net.jitse.npclib.nms.v1_8_R3.NPC_v1_8_R3.getPlayerHologram(NPC_v1_8_R3.java:43) ~[?:?]
at net.jitse.npclib.internal.NPCBase.destroy(NPCBase.java:136) ~[?:?]
```

Currently attempting to validate the fix on my end.

### CODE REVIEW

**Comment by JitseB** [comment]
Were you able to validate it yet?

**Comment by RealGatt** [comment]
Isn't hasn't occurred since adding the fix, on versions 1.8R3, 1.15.1 and 1.16.1.

image
Not sure how this is a conflict, GitHub- nice one 🤣

**Comment by RealGatt** [comment]
After a few more days of testing and validating- I'm happy to say that the issue is fixed.

**Comment by JitseB** [comment]
Alright! Merging PR.

**Comment by JitseB** [comment]
Which I'll have to do manually. Nice... Merging in a bit.

**Comment by RealGatt** [comment]
Rats- was hoping it would just be the space that was causing the conflict. I can't see the conflict here, GitHub >:(

**Comment by JitseB** [comment]
Well, not sure how that was an issue... but okay. Merging!

**Pull request merged**
